## DATA WRANGLING
## Arquivo de apoio para estudo de data wrangling¶

## Notas aula MBA SUP/Esalq - Módulo Data Wrangling IV

In [2]:
# IMPORTAÇÃO DE BANCOS DE DADOS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# pip install xlrd # pacote dependência que read_excel usa para ler arquivos na extensão .xls

In [3]:
#%% Importando o banco de dados

dados_jogos = pd.read_csv('(4.2) Jogos Copa 22.csv', sep=',')

In [7]:
dados_jogos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   match_id                  64 non-null     int64
 1   stage                     64 non-null     object
 2   date                      64 non-null     object
 3   pens                      64 non-null     bool
 4   pens_home_score           64 non-null     object
 5   pens_away_score           64 non-null     object
 6   team_name_home            64 non-null     object
 7   team_name_away            64 non-null     object
 8   team_home_score           64 non-null     int64
 9   team_away_score           64 non-null     int64
 10  possession_home           64 non-null     float64
 11  possession_away           64 non-null     float64
 12  total_shots_home          64 non-null     int64
 13  total_shots_away          64 non-null     int64
 14  shots_on_target_home      64 non-null     int64
 15  shots_on_target_away      64 non-null     int64
 16  duels_won_home            64 non-null     float64
 17  duels_won_away            64 non-null     float64
 18  prediction_team_home_win  64 non-null     float64
 19  prediction_draw           64 non-null     float64
 20  prediction_team_away_win  64 non-null     float64
 21  prediction_quantity       64 non-null     int64
 22  location                  64 non-null     object
 23  events_list               64 non-null     object
 24  lineup_home               64 non-null     object
 25  lineup_away               64 non-null     object
 26  player_names_home         64 non-null     object
 27  player_numbers_home       64 non-null     object
 28  player_names_away         64 non-null     object
 29  player_numbers_away       64 non-null     object
dtypes: bool(1), float64(7), int64(8), object(14)
memory usage: 14.7+ KB

In [23]:
dados_jogos["venceu"] = np.where((dados_jogos['team_home_score']-dados_jogos['team_away_score']>0),\
                                 "Mandante",np.where((dados_jogos['team_home_score']-dados_jogos['team_away_score']<0),\
                                                     "Visitante",np.where((dados_jogos['team_home_score']-dados_jogos['team_away_score']==0),\
                                                                          "Empate","Demais")))

In [24]:
dados_jogos

,match_id,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,...,prediction_quantity,location,events_list,lineup_home,lineup_away,player_names_home,player_numbers_home,player_names_away,player_numbers_away,venceu
0,1,Final,18/12/2022,True,4,2,Argentina,France,3,3,...,1002364,Lusail Iconic Stadium,"[{'event_team': 'home', 'event_time': "" 23' "",...","[{'player_name': ' Di María ', 'player_number'...","[{'player_name': ' Giroud ', 'player_number': ...","['Di María', 'Álvarez', 'Messi', 'Mac Allister...","['11', '9', '10', '20', '24', '7', '3', '19', ...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '14', '8', '22', '18', ...",Empate
1,2,Match for third place,17/12/2022,False,False,False,Croatia,Morocco,2,1,...,367156,Khalifa International Stadium,"[{'event_team': 'home', 'event_time': "" 7' "", ...","[{'player_name': ' Livaja ', 'player_number': ...","[{'player_name': ' Boufal ', 'player_number': ...","['Livaja', 'Oršić', 'Kramarić', 'Majer', 'Kova...","['14', '18', '9', '7', '8', '10', '4', '20', '...","['Boufal', 'En-Nesyri', 'Ziyech', 'Sabiri', 'A...","['17', '19', '7', '11', '4', '23', '25', '20',...",Mandante
2,3,Semi-finals,14/12/2022,False,False,False,France,Morocco,2,0,...,720768,Al Bayt Stadium,"[{'event_team': 'home', 'event_time': "" 5' "", ...","[{'player_name': ' Giroud ', 'player_number': ...","[{'player_name': ' En-Nesyri ', 'player_number...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '13', '8', '22', '24', ...","['En-Nesyri', 'Boufal', 'Amrabat', 'Ounahi', '...","['19', '17', '4', '8', '7', '3', '18', '6', '2...",Mandante
3,4,Semi-finals,13/12/2022,False,False,False,Argentina,Croatia,3,0,...,792326,Lusail Iconic Stadium,"[{'event_team': 'away', 'event_time': "" 32' "",...","[{'player_name': ' Álvarez ', 'player_number':...","[{'player_name': ' Perišić ', 'player_number':...","['Álvarez', 'Messi', 'Mac Allister', 'Fernánde...","['9', '10', '20', '24', '5', '7', '3', '19', '...","['Perišić', 'Kramarić', 'Pašalić', 'Kovačić', ...","['4', '9', '15', '8', '11', '10', '19', '20', ...",Mandante
4,5,Quarter-finals,10/12/2022,False,False,False,England,France,1,2,...,672577,Al Bayt Stadium,"[{'event_team': 'away', 'event_time': "" 17' "",...","[{'player_name': ' Foden ', 'player_number': '...","[{'player_name': ' Giroud ', 'player_number': ...","['Foden', 'Kane', 'Saka', 'Bellingham', 'Rice'...","['20', '9', '17', '22', '4', '8', '3', '6', '5...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '14', '8', '22', '18', ...",Visitante
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,60,Group stage: Matchday 1,22/11/2022,False,False,False,Argentina,Saudi Arabia,1,2,...,657383,Lusail Iconic Stadium,"[{'event_team': 'home', 'event_time': "" 10' "",...","[{'player_name': ' Martínez ', 'player_number'...","[{'player_name': ' Al-Shehri ', 'player_number...","['Martínez', 'Messi', 'Gómez', 'Paredes', 'De ...","['22', '10', '17', '5', '7', '11', '3', '19', ...","['Al-Shehri', 'Al-Dawsari', 'Kanno', 'Al-Faraj...","['11', '10', '23', '7', '9', '8', '13', '5', '...",Visitante
60,61,Group stage: Matchday 1,21/11/2022,False,False,False,USA,Wales,1,1,...,361145,Ahmad bin Ali Stadium,"[{'event_team': 'home', 'event_time': "" 11' "",...","[{'player_name': ' Pulisic ', 'player_number':...","[{'player_name': ' James ', 'player_number': '...","['Pulisic', 'Sargent', 'Weah', 'Musah', 'Adams...","['10', '24', '21', '6', '4', '8', '5', '13', '...","['James', 'Bale', 'Williams', 'Wilson', 'Ampad...","['20', '11', '3', '8', '15', '10', '14', '4', ...",Empate
61,62,Group stage: Matchday 1,21/11/2022,False,False,False,Senegal,Netherlands,0,2,...,457977,Al Thumama Stadium,"[{'event_team': 'away', 'event_time': "" 56' "",...","[{'player_name': ' Dia ', 'player_number': ' 9...","[{'player_name': ' Bergwijn ', 'player_number'...","['Dia', 'Sarr', 'Gueye', 'Diatta', 'Mendy', 'K...","['9', '18', '5', '15', '6', '8', '22', '4', '3...","['Bergwijn', 'Janssen', 'Gakpo', 'Blind', 'De ...","['7', '18', '8', '17', '21', '11', '22', '5', ...",Visitante
62,63,Group stage: Matchday 1,21/11/2022,False,False,False,England,Iran,6,2,...,498752,Khalifa International Stadium,"[{'event_team': 'away', 'event_time': "" 20' "",...","[{'player_name': ' Kane ', 'player_number': ' ...","[{'player_name': ' Taremi ', 'player_number': ...","['Kane', 'Sterling', 'Mount', 'Saka', 'Rice', ...","['9', '10', '19', '17', '4', '22', '3', '6', '...","['Taremi', 'Hajsafi', 'Karimi', 'Nourollahi', ...","['9', '3', '18', '21', '7', '5', '19', '15', '...",Mandante
63,64,Group stage: Matchday 1,20/11/2022,False,False,False,Qatar,Ecuador,0,2,...,528736,Al Bayt Stadium,"[{'event_team': 'away', 'event_time': "" 4' "", ...","[{'player_name': ' Afif ', 'player_number': ' ...","[{'player_name': ' Estrada ', 'player_number':...","['Afif', 'Almoez', 'Abdulaziz', 'Boudiaf', 'Al...","['11', '19', '6', '12', '10', '14', '3', '16',...","['Estrada', 'Valencia', 'Ibarra', 'Caicedo', '...","['11', '13', '10', '23', '20', '19', '7', '3',...",Visitante

In [33]:
# TSubstituir a informação de penaltis para NaN e alterar para tipo float
dados_jogos["pens_home_score"] = dados_jogos['pens_home_score'].replace("False",np.nan)
dados_jogos['pens_away_score']=dados_jogos['pens_away_score'].replace("False",np.nan)
dados_jogos['pens_away_score']=dados_jogos['pens_away_score'].astype("float")
dados_jogos['pens_home_score']=dados_jogos['pens_home_score'].astype("float")

In [34]:
dados_jogos

,match_id,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,...,prediction_quantity,location,events_list,lineup_home,lineup_away,player_names_home,player_numbers_home,player_names_away,player_numbers_away,venceu
0,1,Final,18/12/2022,True,4.0,2.0,Argentina,France,3,3,...,1002364,Lusail Iconic Stadium,"[{'event_team': 'home', 'event_time': "" 23' "",...","[{'player_name': ' Di María ', 'player_number'...","[{'player_name': ' Giroud ', 'player_number': ...","['Di María', 'Álvarez', 'Messi', 'Mac Allister...","['11', '9', '10', '20', '24', '7', '3', '19', ...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '14', '8', '22', '18', ...",Empate
1,2,Match for third place,17/12/2022,False,NaN,NaN,Croatia,Morocco,2,1,...,367156,Khalifa International Stadium,"[{'event_team': 'home', 'event_time': "" 7' "", ...","[{'player_name': ' Livaja ', 'player_number': ...","[{'player_name': ' Boufal ', 'player_number': ...","['Livaja', 'Oršić', 'Kramarić', 'Majer', 'Kova...","['14', '18', '9', '7', '8', '10', '4', '20', '...","['Boufal', 'En-Nesyri', 'Ziyech', 'Sabiri', 'A...","['17', '19', '7', '11', '4', '23', '25', '20',...",Mandante
2,3,Semi-finals,14/12/2022,False,NaN,NaN,France,Morocco,2,0,...,720768,Al Bayt Stadium,"[{'event_team': 'home', 'event_time': "" 5' "", ...","[{'player_name': ' Giroud ', 'player_number': ...","[{'player_name': ' En-Nesyri ', 'player_number...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '13', '8', '22', '24', ...","['En-Nesyri', 'Boufal', 'Amrabat', 'Ounahi', '...","['19', '17', '4', '8', '7', '3', '18', '6', '2...",Mandante
3,4,Semi-finals,13/12/2022,False,NaN,NaN,Argentina,Croatia,3,0,...,792326,Lusail Iconic Stadium,"[{'event_team': 'away', 'event_time': "" 32' "",...","[{'player_name': ' Álvarez ', 'player_number':...","[{'player_name': ' Perišić ', 'player_number':...","['Álvarez', 'Messi', 'Mac Allister', 'Fernánde...","['9', '10', '20', '24', '5', '7', '3', '19', '...","['Perišić', 'Kramarić', 'Pašalić', 'Kovačić', ...","['4', '9', '15', '8', '11', '10', '19', '20', ...",Mandante
4,5,Quarter-finals,10/12/2022,False,NaN,NaN,England,France,1,2,...,672577,Al Bayt Stadium,"[{'event_team': 'away', 'event_time': "" 17' "",...","[{'player_name': ' Foden ', 'player_number': '...","[{'player_name': ' Giroud ', 'player_number': ...","['Foden', 'Kane', 'Saka', 'Bellingham', 'Rice'...","['20', '9', '17', '22', '4', '8', '3', '6', '5...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '14', '8', '22', '18', ...",Visitante
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,60,Group stage: Matchday 1,22/11/2022,False,NaN,NaN,Argentina,Saudi Arabia,1,2,...,657383,Lusail Iconic Stadium,"[{'event_team': 'home', 'event_time': "" 10' "",...","[{'player_name': ' Martínez ', 'player_number'...","[{'player_name': ' Al-Shehri ', 'player_number...","['Martínez', 'Messi', 'Gómez', 'Paredes', 'De ...","['22', '10', '17', '5', '7', '11', '3', '19', ...","['Al-Shehri', 'Al-Dawsari', 'Kanno', 'Al-Faraj...","['11', '10', '23', '7', '9', '8', '13', '5', '...",Visitante
60,61,Group stage: Matchday 1,21/11/2022,False,NaN,NaN,USA,Wales,1,1,...,361145,Ahmad bin Ali Stadium,"[{'event_team': 'home', 'event_time': "" 11' "",...","[{'player_name': ' Pulisic ', 'player_number':...","[{'player_name': ' James ', 'player_number': '...","['Pulisic', 'Sargent', 'Weah', 'Musah', 'Adams...","['10', '24', '21', '6', '4', '8', '5', '13', '...","['James', 'Bale', 'Williams', 'Wilson', 'Ampad...","['20', '11', '3', '8', '15', '10', '14', '4', ...",Empate
61,62,Group stage: Matchday 1,21/11/2022,False,NaN,NaN,Senegal,Netherlands,0,2,...,457977,Al Thumama Stadium,"[{'event_team': 'away', 'event_time': "" 56' "",...","[{'player_name': ' Dia ', 'player_number': ' 9...","[{'player_name': ' Bergwijn ', 'player_number'...","['Dia', 'Sarr', 'Gueye', 'Diatta', 'Mendy', 'K...","['9', '18', '5', '15', '6', '8', '22', '4', '3...","['Bergwijn', 'Janssen', 'Gakpo', 'Blind', 'De ...","['7', '18', '8', '17', '21', '11', '22', '5', ...",Visitante
62,63,Group stage: Matchday 1,21/11/2022,False,NaN,NaN,England,Iran,6,2,...,498752,Khalifa International Stadium,"[{'event_team': 'away', 'event_time': "" 20' "",...","[{'player_name': ' Kane ', 'player_number': ' ...","[{'player_name': ' Taremi ', 'player_number': ...","['Kane', 'Sterling', 'Mount', 'Saka', 'Rice', ...","['9', '10', '19', '17', '4', '22', '3', '6', '...","['Taremi', 'Hajsafi', 'Karimi', 'Nourollahi', ...","['9', '3', '18', '21', '7', '5', '19', '15', '...",Mandante
63,64,Group stage: Matchday 1,20/11/2022,False,NaN,NaN,Qatar,Ecuador,0,2,...,528736,Al Bayt Stadium,"[{'event_team': 'away', 'event_time': "" 4' "", ...","[{'player_name': ' Afif ', 'player_number': ' ...","[{'player_name': ' Estrada ', 'player_number':...","['Afif', 'Almoez', 'Abdulaziz', 'Boudiaf', 'Al...","['11', '19', '6', '12', '10', '14', '3', '16',...","['Estrada', 'Valencia', 'Ibarra', 'Caicedo', '...","['11', '13', '10', '23', '20', '19', '7', '3',...",Visitante

In [37]:
# Ajustando a variável com o time vencedor
dados_jogos["vencedor"] = np.where(dados_jogos['pens_home_score']-dados_jogos['pens_home_score']>0,"Mandante",\
                                   np.where(dados_jogos['pens_home_score']-dados_jogos['pens_home_score']<0,\
                                            "Visitante",np.where(dados_jogos['pens_home_score'].isna(),dados_jogos["venceu"],\
                                            "Demais")))
#na última linha, onde não houve pênalti, usa o resultado do DataFrame anterior, com a variável "venceu"

In [36]:
dados_jogos

,match_id,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,...,location,events_list,lineup_home,lineup_away,player_names_home,player_numbers_home,player_names_away,player_numbers_away,venceu,vencedor
0,1,Final,18/12/2022,True,4.0,2.0,Argentina,France,3,3,...,Lusail Iconic Stadium,"[{'event_team': 'home', 'event_time': "" 23' "",...","[{'player_name': ' Di María ', 'player_number'...","[{'player_name': ' Giroud ', 'player_number': ...","['Di María', 'Álvarez', 'Messi', 'Mac Allister...","['11', '9', '10', '20', '24', '7', '3', '19', ...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '14', '8', '22', '18', ...",Empate,Demais
1,2,Match for third place,17/12/2022,False,NaN,NaN,Croatia,Morocco,2,1,...,Khalifa International Stadium,"[{'event_team': 'home', 'event_time': "" 7' "", ...","[{'player_name': ' Livaja ', 'player_number': ...","[{'player_name': ' Boufal ', 'player_number': ...","['Livaja', 'Oršić', 'Kramarić', 'Majer', 'Kova...","['14', '18', '9', '7', '8', '10', '4', '20', '...","['Boufal', 'En-Nesyri', 'Ziyech', 'Sabiri', 'A...","['17', '19', '7', '11', '4', '23', '25', '20',...",Mandante,Mandante
2,3,Semi-finals,14/12/2022,False,NaN,NaN,France,Morocco,2,0,...,Al Bayt Stadium,"[{'event_team': 'home', 'event_time': "" 5' "", ...","[{'player_name': ' Giroud ', 'player_number': ...","[{'player_name': ' En-Nesyri ', 'player_number...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '13', '8', '22', '24', ...","['En-Nesyri', 'Boufal', 'Amrabat', 'Ounahi', '...","['19', '17', '4', '8', '7', '3', '18', '6', '2...",Mandante,Mandante
3,4,Semi-finals,13/12/2022,False,NaN,NaN,Argentina,Croatia,3,0,...,Lusail Iconic Stadium,"[{'event_team': 'away', 'event_time': "" 32' "",...","[{'player_name': ' Álvarez ', 'player_number':...","[{'player_name': ' Perišić ', 'player_number':...","['Álvarez', 'Messi', 'Mac Allister', 'Fernánde...","['9', '10', '20', '24', '5', '7', '3', '19', '...","['Perišić', 'Kramarić', 'Pašalić', 'Kovačić', ...","['4', '9', '15', '8', '11', '10', '19', '20', ...",Mandante,Mandante
4,5,Quarter-finals,10/12/2022,False,NaN,NaN,England,France,1,2,...,Al Bayt Stadium,"[{'event_team': 'away', 'event_time': "" 17' "",...","[{'player_name': ' Foden ', 'player_number': '...","[{'player_name': ' Giroud ', 'player_number': ...","['Foden', 'Kane', 'Saka', 'Bellingham', 'Rice'...","['20', '9', '17', '22', '4', '8', '3', '6', '5...","['Giroud', 'Mbappé', 'Griezmann', 'Dembélé', '...","['9', '10', '7', '11', '14', '8', '22', '18', ...",Visitante,Visitante
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,60,Group stage: Matchday 1,22/11/2022,False,NaN,NaN,Argentina,Saudi Arabia,1,2,...,Lusail Iconic Stadium,"[{'event_team': 'home', 'event_time': "" 10' "",...","[{'player_name': ' Martínez ', 'player_number'...","[{'player_name': ' Al-Shehri ', 'player_number...","['Martínez', 'Messi', 'Gómez', 'Paredes', 'De ...","['22', '10', '17', '5', '7', '11', '3', '19', ...","['Al-Shehri', 'Al-Dawsari', 'Kanno', 'Al-Faraj...","['11', '10', '23', '7', '9', '8', '13', '5', '...",Visitante,Visitante
60,61,Group stage: Matchday 1,21/11/2022,False,NaN,NaN,USA,Wales,1,1,...,Ahmad bin Ali Stadium,"[{'event_team': 'home', 'event_time': "" 11' "",...","[{'player_name': ' Pulisic ', 'player_number':...","[{'player_name': ' James ', 'player_number': '...","['Pulisic', 'Sargent', 'Weah', 'Musah', 'Adams...","['10', '24', '21', '6', '4', '8', '5', '13', '...","['James', 'Bale', 'Williams', 'Wilson', 'Ampad...","['20', '11', '3', '8', '15', '10', '14', '4', ...",Empate,Empate
61,62,Group stage: Matchday 1,21/11/2022,False,NaN,NaN,Senegal,Netherlands,0,2,...,Al Thumama Stadium,"[{'event_team': 'away', 'event_time': "" 56' "",...","[{'player_name': ' Dia ', 'player_number': ' 9...","[{'player_name': ' Bergwijn ', 'player_number'...","['Dia', 'Sarr', 'Gueye', 'Diatta', 'Mendy', 'K...","['9', '18', '5', '15', '6', '8', '22', '4', '3...","['Bergwijn', 'Janssen', 'Gakpo', 'Blind', 'De ...","['7', '18', '8', '17', '21', '11', '22', '5', ...",Visitante,Visitante
62,63,Group stage: Matchday 1,21/11/2022,False,NaN,NaN,England,Iran,6,2,...,Khalifa International Stadium,"[{'event_team': 'away', 'event_time': "" 20' "",...","[{'player_name': ' Kane ', 'player_number': ' ...","[{'player_name': ' Taremi ', 'player_number': ...","['Kane', 'Sterling', 'Mount', 'Saka', 'Rice', ...","['9', '10', '19', '17', '4', '22', '3', '6', '...","['Taremi', 'Hajsafi', 'Karimi', 'Nourollahi', ...","['9', '3', '18', '21', '7', '5', '19', '15', '...",Mandante,Mandante
63,64,Group stage: Matchday 1,20/11/2022,False,NaN,NaN,Qatar,Ecuador,0,2,...,Al Bayt Stadium,"[{'event_team': 'away', 'event_time': "" 4' "", ...","[{'player_name': ' Afif ', 'player_number': ' ...","[{'player_name': ' Estrada ', 'player_number':...","['Afif', 'Almoez', 'Abdulaziz', 'Boudiaf', 'Al...","['11', '19', '6', '12', '10', '14', '3', '16',...","['Estrada', 'Valencia', 'Ibarra', 'Caicedo', '...","['11', '13', '10', '23', '20', '19', '7', '3',...",Visitante,Visitante

In [ ]:
# eliminar a variável da base anterior
dados_jogos.drop(columns=["venceu"],inplace=