## DATA WRANGLING
## Arquivo de apoio para estudo de data wrangling¶

## Notas aula MBA SUP/Esalq - Módulo Data Wrangling III

In [1]:
# IMPORTAÇÃO DE BANCOS DE DADOS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# pip install xlrd # pacote dependência que read_excel usa para ler arquivos na extensão .xls

In [9]:
dados_wdi = pd.read_excel("(2.2) WDI World Bank.xlsx", na_values='..')

In [10]:
dados_wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383577 entries, 0 to 383576
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Country Name   383574 non-null  object
 1   Country Code   383572 non-null  object
 2   Series Name    383572 non-null  object
 3   Series Code    383572 non-null  object
 4   2021 [YR2021]  108687 non-null  float64
 5   Topic          383572 non-null  object
dtypes: float64(1), object(5)
memory usage: 17.6+ MB

In [19]:
#Verificando elementos únicos das variáveis
len(dados_wdi["Country Name"].unique())

269

In [20]:
#Verificando elementos únicos das variáveis
len(dados_wdi["Series Name"].unique())

1443

In [21]:
#Verificando elementos únicos das variáveis
len(dados_wdi["Topic"].unique())

90

In [22]:
dados_wdi.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '2021 [YR2021]', 'Topic'],
      dtype='object')

In [23]:
#Alterar nome das variáveis
dados_wdi.rename(columns={"Country Name":"pais","Country Code":"cod_pais","Series Name":"serie",\
                          "2021 [YR2021]":"ano_2021","Topic":"topico"},inplace=True)

In [25]:
# analisando as últimas linhas do dataset

dados_wdi.tail(n=20)

,pais,cod_pais,serie,Series Code,ano_2021,topico
383557,World,WLD,"Water productivity, total (constant 2015 US$ G...",ER.GDP.FWTL.M3.KD,NaN,Environment: Freshwater
383558,World,WLD,Wholesale price index (2010 = 100),FP.WPI.TOTL,NaN,Financial Sector: Exchange rates & prices
383559,World,WLD,Women Business and the Law Index Score (scale ...,SG.LAW.INDX,76.546053,Gender: Public life & decision making
383560,World,WLD,Women making their own informed decisions rega...,SG.DMK.SRCR.FN.ZS,NaN,Gender: Public life & decision making
383561,World,WLD,Women participating in the three decisions (ow...,SG.DMK.ALLD.FN.ZS,NaN,Gender: Public life & decision making
383562,World,WLD,Women who believe a husband is justified in be...,SG.VAW.REAS.ZS,NaN,Gender: Health
383563,World,WLD,Women who believe a husband is justified in be...,SG.VAW.ARGU.ZS,NaN,Gender: Health
383564,World,WLD,Women who believe a husband is justified in be...,SG.VAW.BURN.ZS,NaN,Gender: Health
383565,World,WLD,Women who believe a husband is justified in be...,SG.VAW.GOES.ZS,NaN,Gender: Health
383566,World,WLD,Women who believe a husband is justified in be...,SG.VAW.NEGL.ZS,NaN,Gender: Health
383567,World,WLD,Women who believe a husband is justified in be...,SG.VAW.REFU.ZS,NaN,Gender: Health
383568,World,WLD,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,Gender: Agency
383569,World,WLD,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,Gender: Agency
383570,World,WLD,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,53.800000,Health: Risk factors
383571,World,WLD,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,400000.000000,Health: Risk factors
383572,NaN,NaN,NaN,NaN,NaN,NaN
383573,NaN,NaN,NaN,NaN,NaN,NaN
383574,NaN,NaN,NaN,NaN,NaN,NaN
383575,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN
383576,Last Updated: 03/30/2023,NaN,NaN,NaN,NaN,NaN

In [29]:
# retirar as últimas linhas, são referências, não observações
dados_wdi = dados_wdi.iloc[0:383572,]

In [30]:
dados_wdi.tail(n=20)

,pais,cod_pais,serie,Series Code,ano_2021,topico
383552,World,WLD,"Vulnerable employment, total (% of total emplo...",SL.EMP.VULN.ZS,NaN,Social Protection & Labor: Economic activity
383553,World,WLD,"Wage and salaried workers, female (% of female...",SL.EMP.WORK.FE.ZS,NaN,Social Protection & Labor: Economic activity
383554,World,WLD,"Wage and salaried workers, male (% of male emp...",SL.EMP.WORK.MA.ZS,NaN,Social Protection & Labor: Economic activity
383555,World,WLD,"Wage and salaried workers, total (% of total e...",SL.EMP.WORK.ZS,NaN,Social Protection & Labor: Economic activity
383556,World,WLD,Wanted fertility rate (births per woman),SP.DYN.WFRT,NaN,Health: Reproductive health
383557,World,WLD,"Water productivity, total (constant 2015 US$ G...",ER.GDP.FWTL.M3.KD,NaN,Environment: Freshwater
383558,World,WLD,Wholesale price index (2010 = 100),FP.WPI.TOTL,NaN,Financial Sector: Exchange rates & prices
383559,World,WLD,Women Business and the Law Index Score (scale ...,SG.LAW.INDX,76.546053,Gender: Public life & decision making
383560,World,WLD,Women making their own informed decisions rega...,SG.DMK.SRCR.FN.ZS,NaN,Gender: Public life & decision making
383561,World,WLD,Women participating in the three decisions (ow...,SG.DMK.ALLD.FN.ZS,NaN,Gender: Public life & decision making
383562,World,WLD,Women who believe a husband is justified in be...,SG.VAW.REAS.ZS,NaN,Gender: Health
383563,World,WLD,Women who believe a husband is justified in be...,SG.VAW.ARGU.ZS,NaN,Gender: Health
383564,World,WLD,Women who believe a husband is justified in be...,SG.VAW.BURN.ZS,NaN,Gender: Health
383565,World,WLD,Women who believe a husband is justified in be...,SG.VAW.GOES.ZS,NaN,Gender: Health
383566,World,WLD,Women who believe a husband is justified in be...,SG.VAW.NEGL.ZS,NaN,Gender: Health
383567,World,WLD,Women who believe a husband is justified in be...,SG.VAW.REFU.ZS,NaN,Gender: Health
383568,World,WLD,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,Gender: Agency
383569,World,WLD,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,Gender: Agency
383570,World,WLD,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,53.800000,Health: Risk factors
383571,World,WLD,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,400000.000000,Health: Risk factors

In [ ]:
# Selecionando os tópicos de saúde
dados_saude = dados_wdi