## DATA WRANGLING
## Arquivo de apoio para estudo de data wrangling

In [8]:
# IMPORTAÇÃO DE BANCOS DE DADOS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
# Importando banco de dados
dados_tempo = pd.read_excel('(1.2) dataset_principal.xls')
dados_merge = pd.read_excel('(1.3) dataset_join.xls')

In [ ]:
#Configurar para visualizar objetos no console
pd.set_option("display.max.columns",None)
print(dados_tempo)

In [22]:
#Função info - retorna informações do banco de dados
# df.rename(columns={"xx":"yy"}
dados_tempo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Estudante                                        10 non-null     object
 1   Tempo para chegar à escola (minutos)             10 non-null     int64
 2   Distância percorrida até a escola (quilômetros)  10 non-null     int64
 3   Quantidade de semáforos                          10 non-null     int64
 4   Período do dia                                   10 non-null     object
 5   Perfil ao volante                                10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [61]:
# Função rename - utilizada para alterar nome das variáveis
dados_tempo.rename(columns={"Estudante":"estudante","Tempo para chegar à escola (minutos)":"tempo","Distância percorrida até a escola (quilômetros)":"distancia",\
                           "Quantidade de semáforos":"semaforos","Período do dia":"periodo","Perfil ao volante":"perfil"},inplace=True)

In [29]:
# Para renomear usando a posição, pode-se utilizar df.columns[index]
dados_novo = dados_tempo.rename(columns={dados_tempo.columns[0]:"obs",dados_tempo.columns[1]:"temp",dados_tempo.columns[5]:"perf",dados_tempo.columns[2]:"dist",\
                                        dados_tempo.columns[3]:"semaforos"})

In [30]:
dados_novo

           obs  temp  dist  semaforos Período do dia       perf
0     Gabriela    15     8          0          Manhã      calmo
1       Dalila    20     6          1          Manhã   moderado
2      Gustavo    20    15          0          Manhã   moderado
3      Letícia    40    20          1          Tarde  agressivo
4  Luiz Ovídio    50    25          2          Tarde  agressivo
5       Leonor    25    11          1          Manhã   moderado
6          Ana    10     5          0          Manhã      calmo
7      Antônio    55    32          3          Tarde      calmo
8        Júlia    35    28          1          Manhã   moderado
9      Mariana    30    20          1          Manhã   moderado

In [33]:
# Para reescrever o mesmo objeto, pode-se utilizar o argumento inplace = True. A diferença para o anterior é que aqui estou alterando
# o próprio objeto ao invés de criar um novo 
dados_novo.rename(columns={"obs":"observacao","temp":"tempo"},inplace=True)

In [45]:
# Selecionando com base na posição
# usar a função iloc[linha, coluna]   use : para incluir todos os valores de linhas ou todos de colunas
dados_novo.iloc[3,]

observacao          Letícia
tempo                    40
dist                     20
semaforos                 1
Período do dia        Tarde
perf              agressivo
Name: 3, dtype: object

In [46]:
dados_novo.iloc[:,4]

0    Manhã
1    Manhã
2    Manhã
3    Tarde
4    Tarde
5    Manhã
6    Manhã
7    Tarde
8    Manhã
9    Manhã
Name: Período do dia, dtype: object

In [48]:
dados_novo.iloc[2:5,]

    observacao  tempo  dist  semaforos Período do dia       perf
2      Gustavo     20    15          0          Manhã   moderado
3      Letícia     40    20          1          Tarde  agressivo
4  Luiz Ovídio     50    25          2          Tarde  agressivo

In [50]:
dados_novo.iloc[:,3:5]
# O índice sempre conta o anterior

   semaforos Período do dia
0          0          Manhã
1          1          Manhã
2          0          Manhã
3          1          Tarde
4          2          Tarde
5          1          Manhã
6          0          Manhã
7          3          Tarde
8          1          Manhã
9          1          Manhã

In [52]:
dados_novo.iloc[2:4,3:5]

   semaforos Período do dia
2          0          Manhã
3          1          Tarde

In [53]:
dados_novo.iloc[5,4]

'Manhã'

In [62]:
#Detalhar uma variável em específico pelo nome
var_tempo = dados_tempo["tempo"]

In [70]:
# É possível acessar uma variável usando dois métodos
# df["variavel"]
# df.variavel
dados_tempo["perfil"]
dados_tempo.perfil

0        calmo
1     moderado
2     moderado
3    agressivo
4    agressivo
5     moderado
6        calmo
7        calmo
8     moderado
9     moderado
Name: perfil, dtype: object

In [71]:
#Se for mais de uma variável, inserir o argumento como uma lista
dados_tempo[["tempo","perfil"]]

   tempo     perfil
0     15      calmo
1     20   moderado
2     20   moderado
3     40  agressivo
4     50  agressivo
5     25   moderado
6     10      calmo
7     55      calmo
8     35   moderado
9     30   moderado

In [76]:
# Para selecionar variáveis por meio de um início em comum
# df.loc[:,df.columns.str.startswith("name")]
dados_tempo.loc[:,dados_tempo.columns.str.startswith("per")]

  periodo     perfil
0   Manhã      calmo
1   Manhã   moderado
2   Manhã   moderado
3   Tarde  agressivo
4   Tarde  agressivo
5   Manhã   moderado
6   Manhã      calmo
7   Tarde      calmo
8   Manhã   moderado
9   Manhã   moderado

In [81]:
# Para selecionar variáveis por meio de um final comum
# df.loc[:,df.columns.str.endswith("name")]
dados_tempo.loc[:,dados_tempo.columns.str.endswith("o")]

   tempo periodo
0     15   Manhã
1     20   Manhã
2     20   Manhã
3     40   Tarde
4     50   Tarde
5     25   Manhã
6     10   Manhã
7     55   Tarde
8     35   Manhã
9     30   Manhã

In [89]:
# Para adicionar uma variável a um dataset existente
# df["variavel_nova"] = lista
idade = pd.Series([25,30,22,28,27,40,42,35,31,29])
dados_novo["idade"] = idade
dados_novo.rename(columns={"Período do dia":"periodo"},inplace=True)
print (dados_novo)

    observacao  tempo  dist  semaforos periodo       perf  idade
0     Gabriela     15     8          0   Manhã      calmo     25
1       Dalila     20     6          1   Manhã   moderado     30
2      Gustavo     20    15          0   Manhã   moderado     22
3      Letícia     40    20          1   Tarde  agressivo     28
4  Luiz Ovídio     50    25          2   Tarde  agressivo     27
5       Leonor     25    11          1   Manhã   moderado     40
6          Ana     10     5          0   Manhã      calmo     42
7      Antônio     55    32          3   Tarde      calmo     35
8        Júlia     35    28          1   Manhã   moderado     31
9      Mariana     30    20          1   Manhã   moderado     29

In [102]:
# Adicionando linhas ao banco de dados
# Usar a função concat
# df_concat = pd.concat([df existente,df a ser concatenado]) #ATENÇÃO: O argumento é uma lista, atenção aos colchetes
# Se quiser reiniciar o índice, incluir .reset_index(drop=True)

# novo registro
nova_obs = pd.DataFrame({"periodo":["Tarde"],"observacao":["Roberto"],"tempo":[40]})

# concatenando tudo
dados_concat = pd.concat([dados_novo,nova_obs]).reset_index(drop = True)
print(dados_concat)

# Neste exemplo, observe que os valores faltantes entraram como Nan

     observacao  tempo  dist  semaforos periodo       perf  idade
0      Gabriela     15   8.0        0.0   Manhã      calmo   25.0
1        Dalila     20   6.0        1.0   Manhã   moderado   30.0
2       Gustavo     20  15.0        0.0   Manhã   moderado   22.0
3       Letícia     40  20.0        1.0   Tarde  agressivo   28.0
4   Luiz Ovídio     50  25.0        2.0   Tarde  agressivo   27.0
5        Leonor     25  11.0        1.0   Manhã   moderado   40.0
6           Ana     10   5.0        0.0   Manhã      calmo   42.0
7       Antônio     55  32.0        3.0   Tarde      calmo   35.0
8         Júlia     35  28.0        1.0   Manhã   moderado   31.0
9       Mariana     30  20.0        1.0   Manhã   moderado   29.0
10      Roberto     40   NaN        NaN   Tarde        NaN    NaN

In [109]:
# Criar uma variável em função de outras duas
# No exemplo abaixo foi arredondado para duas casas decimais
dados_novo["sem km"] = round((dados_novo["semaforos"]/dados_novo["dist"]),2)
print(dados_novo)

    observacao  tempo  dist  semaforos periodo       perf  idade  sem km
0     Gabriela     15     8          0   Manhã      calmo     25    0.00
1       Dalila     20     6          1   Manhã   moderado     30    0.17
2      Gustavo     20    15          0   Manhã   moderado     22    0.00
3      Letícia     40    20          1   Tarde  agressivo     28    0.05
4  Luiz Ovídio     50    25          2   Tarde  agressivo     27    0.08
5       Leonor     25    11          1   Manhã   moderado     40    0.09
6          Ana     10     5          0   Manhã      calmo     42    0.00
7      Antônio     55    32          3   Tarde      calmo     35    0.09
8        Júlia     35    28          1   Manhã   moderado     31    0.04
9      Mariana     30    20          1   Manhã   moderado     29    0.05

In [115]:
# Trocar rótulo de determinadas variáveis
# Usar a função "assign", que adiciona variáveis ao dataset, e a função "map", que aplica uma função a todos os elementos da lista

# Criar dicionário com labels
labels = {"calmo":"perfil_A","moderado":"perfil_B","agressivo":"perfil_C"}

df_labels = dados_tempo.assign(novo_perfil = dados_tempo.perfil.map(labels)) # criei a nova variável novo_perfil por segurança, para rastreabilidade e por
# exigência da função "assign"
df_labels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   estudante    10 non-null     object
 1   tempo        10 non-null     int64
 2   distancia    10 non-null     int64
 3   semaforos    10 non-null     int64
 4   periodo      10 non-null     object
 5   perfil       10 non-null     object
 6   novo_perfil  10 non-null     object
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes

In [ ]:
# parei na linha 171