## DATA WRANGLING
## Python for Data Analysis - Wes McKinney

##  Chapter 7 - Data cleaning and preparation

In [5]:
# IMPORTAÇÃO DE BANCOS DE DADOS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# pip install xlrd # pacote dependência que read_excel usa para ler arquivos na extensão .xls

In [6]:
# Data preparation: loading, cleaning, transforming and rearranging

In [7]:
# Handling missing data
# Pandas uses NaN (Not a Number) to represent missing data (for data with float64 dtype)
# The float64 data type is a 64-bit, double-precision floating-point format used to store decimal numbers in computing
# It is the standard numeric type for decimals in Python (and the default in libraries like NumPy and Pandas)

float_data = pd.Series([1.2,-3.5,np.nan,0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [8]:
# method isna() gives us a Boolean Series where values are null
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [9]:
# Built-in Python None is treated as NA (Not available)
string_data = pd.Series(["aardvark",np.nan,None,"avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [10]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [11]:
float_data = pd.Series([1,2,None],dtype = "float64")
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
# None é um objeto nativo do Python. Significa "ausência de valor" na linguagem em si. 
# Funciona bem em listas, dicionários, lógica condicional. O problema é que None é um objeto
# Num array de inteiros, inserir None força o pandas a converter tudo para object dtype 
# — porque agora o array precisa guardar tanto números quanto um objeto Python. Isso é lento e desperdiça memória.

# np.nan (Not a Number) vem do NumPy e é um valor especial do padrão IEEE 754 de ponto flutuante. É um float — não um objeto Python arbitrário.
# Isso significa que ele cabe dentro de um array numérico sem forçar conversão de tipo. Operações matemáticas com ele não geram erro, propagam o nan

# O que é float64
# É um tipo de dado numérico de ponto flutuante com 64 bits de precisão.
# O "64" refere-se à quantidade de bits usados para armazenar o número na memória — quanto mais bits, maior a precisão e o intervalo representável.
# É o tipo numérico padrão do NumPy e do pandas para dados decimais.
# Quando você cria uma Series com números e não especifica dtype, o pandas provavelmente vai usar float64.

In [13]:
# NA handling object methods
# dropna - filter axis labels based on wheter valure for each label have missinf data
# fillna = fill in missing data with some value or usin an interpolation method such as "ffill" or "bfill"
# isna - return Boolean value indicatin which values are missing/NA
# notna - negation od isna

In [14]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [15]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
# dropna equivale ao seguinte filtro:
data[data.notna()] #retorna somente as linhas com boleano True

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
# Em um dataframe, dropna() remove cada linha que possua valor NA. se usar o argumento how = "all", será retirada somente a linha que tuver todos os valores nulos
data = pd.DataFrame([[1.,6.5,3.],[1,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [19]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
# para excluir colunas, inclua o argumento  axis = "columns"

data[4]=np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis="columns",how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
# argumento thresh
# thresh=x significa: mantenha a linha se ela tiver pelo menos x valores não-nulos

#criar o dataframe
df = pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[:4,1]=np.nan
df.iloc[:2,2]=np.nan
df

          0         1         2
0 -1.569745       NaN       NaN
1  0.524034       NaN       NaN
2 -0.997505       NaN -0.642221
3 -0.597410       NaN  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [23]:
df.dropna(thresh=2)

          0         1         2
2 -0.997505       NaN -0.642221
3 -0.597410       NaN  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [24]:
## Prenchendo data faltante

In [25]:
# função fillna
# permite preencher NA com um valor específico
# diminui o risco de descartar outros dados quando se descarta NA
df

          0         1         2
0 -1.569745       NaN       NaN
1  0.524034       NaN       NaN
2 -0.997505       NaN -0.642221
3 -0.597410       NaN  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [26]:
df.fillna(0)

          0         1         2
0 -1.569745  0.000000  0.000000
1  0.524034  0.000000  0.000000
2 -0.997505  0.000000 -0.642221
3 -0.597410  0.000000  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [27]:
# Se usar um dicionário, é possível personalizar cada coluna com um valor diferente
df

          0         1         2
0 -1.569745       NaN       NaN
1  0.524034       NaN       NaN
2 -0.997505       NaN -0.642221
3 -0.597410       NaN  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [28]:
df.fillna({1:0.57,2:0.12})

          0         1         2
0 -1.569745  0.570000  0.120000
1  0.524034  0.570000  0.120000
2 -0.997505  0.570000 -0.642221
3 -0.597410  0.570000  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [29]:
# função ffill - forward fill
# Propaga o último valor válido para baixo, preenchendo os NaNs seguintes com o valor anterior mais próximo
# O nome vem de forward — ele olha para trás (o valor que já passou) e preenche para frente
# parâmetro limit: limit=n restringe a propagação a no máximo n posições consecutivas a partir do último valor válido. O que exceder permanece NaN

# O inverso do ffill é o bfill (backward fill) — preenche com o próximo valor válido, olhando para frente.

df

          0         1         2
0 -1.569745       NaN       NaN
1  0.524034       NaN       NaN
2 -0.997505       NaN -0.642221
3 -0.597410       NaN  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [30]:
df.fillna(method="bfill")

C:\Users\Bruno\AppData\Local\Temp\ipykernel_18892\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

          0         1         2
0 -1.569745 -0.237927 -0.642221
1  0.524034 -0.237927 -0.642221
2 -0.997505 -0.237927 -0.642221
3 -0.597410 -0.237927  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [31]:
df.bfill()

          0         1         2
0 -1.569745 -0.237927 -0.642221
1  0.524034 -0.237927 -0.642221
2 -0.997505 -0.237927 -0.642221
3 -0.597410 -0.237927  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [32]:
# pode-se preencher com cálculos estatísticos. e.g. média
df.fillna(df.mean())

          0         1         2
0 -1.569745 -0.134511  0.467496
1  0.524034 -0.134511  0.467496
2 -0.997505 -0.134511 -0.642221
3 -0.597410 -0.134511  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

In [33]:
# pode-se preencher com cálculos estatísticos. e.g. mediana
df.fillna(df.median())

          0         1         2
0 -1.569745 -0.237927  0.301958
1  0.524034 -0.237927  0.301958
2 -0.997505 -0.237927 -0.642221
3 -0.597410 -0.237927  0.640377
4 -1.099559 -0.237927  0.301958
5  0.203502  0.385630 -0.011402
6  0.576453 -0.551238  2.048770

## parei na página 209